### ISSUE TITLE
Dump without showing pointer addresses

### ISSUE THREAD

**Issue by felixge** [davecgh/go-spew#18]
Hi,

I'd like to use spew in combination with a text diff pkg to show useful error messages when deep equality checks fail in my test cases. Ideally I'd like to have the same output as Dump(), but without the pointer addresses showing. Would you be interested in a patch for this? I'd be happy to propose an API for it first or take a suggestion from you.

Cheers,
Felix

**Comment by flimzy** [comment]
I would really like to see this feature as well. As things stand, I'm compensating by piping the result of `Sdump()` through some regular expressions to normalize addresses, as well as slice capacities. I'd much rather have the option to not output these things, since they aren't meaningful when comparing two data structures in my application.
