### ISSUE TITLE
Printing []byte panics

### ISSUE THREAD

**Issue by JoeBruner** [davecgh/go-spew#26]
Maybe I'm missing something, but when I try to print out my [bson.D](http://godoc.org/labix.org/v2/mgo/bson#D) stuct, it works fine if there is no binary data in it, but if I put in []uint8, it barfs.  As a simple example, this will panic:

    foo := []byte { byte(41) }
    spew.Dump(foo)

which produces 

    panic: runtime error: invalid memory address or nil pointer dereference

**Comment by shurcooL** [comment]
Cannot reproduce locally. The snippet you've posted runs as expected for me. It's also covered by tests.

What does `go version` print? Try doing `go get -u github.com/davecgh/go-spew/spew` and see if it helps.

**Comment by JoeBruner** [comment]
`go version` is 

    go version go1.4 linux/amd64

I tried the program again and it didn't work. I then did the `go get -u` and it fixed it.  Don't know why I didn't think to try that.  Thanks.

**Comment by JoeBruner** [comment]
For what it's worth, I just upgraded to 1.4.1 from 1.3.  Wonder if that had something to do with it?

**Comment by davecgh** [comment]
Yes, that would be why. The go runtime changed the memory layout of the reflect stucts that spew uses to perform some of its magic in between `go1.3.3` and `go1.4`.  It was fixed in spew while it was still on go tip well before `go1.4` shipped, but older versions of spew (before commit 128854244a4ac24b718da3d5f79cf5541c81ee56 to be precise) will panic on the `go1.4+` runtime.
