### ISSUE TITLE
spewing a slice with go1.4.1

### ISSUE THREAD

**Issue by hagna** [davecgh/go-spew#28]
This panics with go 1.4.1:

package main

import "github.com/davecgh/go-spew/spew"

func main() {
	c := [102]byte{}
	spew.Dump(c[:100])
}

**Comment by davecgh** [comment]
Make sure you're running the latest version of spew (`go get -u github.com/davecgh/go-spew/spew`).  This was fixed months ago.  Running it locally:

```Go
([]uint8) (len=100 cap=102) {
 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000060  00 00 00 00                                       |....|
}
```

**Comment by shurcooL** [comment]
Your README installation step currently says `go get github.com/davecgh/go-spew/spew`, perhaps it's worth changing to `go get -u github.com/davecgh/go-spew/spew`?

**Comment by davecgh** [comment]
I can add a section about updating that includes that.  I'm not sure if the -u (upgrade) flag works if you don't already have the package.

**Comment by shurcooL** [comment]
> I'm not sure if the -u (upgrade) flag works if you don't already have the package.

It absolutely does.

That's why IMO it's a better default to list in READMEs. If you're missing the package, it will fetch the latest, and if you happen to have an old version, it will update it instead of leaving you with an old version.

Also, if your package depends on the latest version of another dependency, and the user happens to have an outdated (and broken) version of that dependency, -u will update it, which results in a predictable state.

**Comment by davecgh** [comment]
Ok, good to know.  I'll update it. Thanks!
